version: '3.8'
services:
  db:
    image: postgres:15.2
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: nest-challenge-db
    networks:
      - nest-challenge-db

networks:
  nest-challenge-db: