version: '3.8'
services:
  db:
    image: postgres:15.2
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
    networks:
      - nest-challenge-db

networks:
  nest-challenge-db: